# Generated by Django 4.2.4 on 2023-08-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headding', models.CharField(blank=True, max_length=600)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('para1', models.CharField(blank=True, max_length=1200)),
                ('para2', models.CharField(blank=True, max_length=1200)),
                ('tag', models.CharField(blank=True, max_length=600)),
                ('img', models.ImageField(upload_to='images')),
                ('author', models.CharField(max_length=350)),
                ('category', models.CharField(blank=True, default='None', max_length=100)),
                ('youtube', models.URLField(blank=True, max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatapp', models.URLField(blank=True, max_length=900)),
                ('youtube', models.URLField(blank=True, max_length=900)),
                ('twitter', models.URLField(blank=True, max_length=900)),
                ('facebook', models.URLField(blank=True, max_length=900)),
            ],
        ),
    ]
