# Generated by Django 4.2.4 on 2023-08-19 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Sport', 'Sport'), ('Education', 'Education')], default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='headding',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='news',
            name='para1',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='news',
            name='para2',
            field=models.TextField(blank=True, max_length=1200),
        ),
    ]
