# Generated by Django 4.2.4 on 2023-09-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headding', models.TextField(blank=True, max_length=600)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('para1', models.TextField(blank=True, max_length=1200)),
                ('para2', models.TextField(blank=True, max_length=1200)),
                ('tag', models.CharField(blank=True, max_length=600)),
                ('img', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=350)),
                ('youtube', models.CharField(blank=True, max_length=900)),
                ('category', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='siteadmin.category')),
            ],
        ),
    ]
